FROM stagex/pallet-rust:1.94.0@sha256:4e2d4273a1d5c6d62660968302791f3cf550c3d12629e66314956ff46c97fc0e AS build

ENV RUSTFLAGS='-C target-feature=+crt-static'
ENV CARGOFLAGS='--target x86_64-unknown-linux-musl --no-default-features --locked --release'
ENV RELEASE_DIR=/src/target/x86_64-unknown-linux-musl/release
ENV APPLICATION_CRATE_NAME=dlc-verify-tvc

ADD Cargo.toml Cargo.lock rust-toolchain.toml /src/
ADD crates /src/crates
WORKDIR /src/
RUN cargo fetch

WORKDIR /src/crates/${APPLICATION_CRATE_NAME}
RUN --network=none <<-EOF
    set -eu
    cargo build ${CARGOFLAGS}
    mkdir -p /rootfs
    mv ${RELEASE_DIR}/${APPLICATION_CRATE_NAME} /rootfs/tvc_app
EOF

FROM stagex/core-busybox:1.36.1@sha256:cac5d773db1c69b832d022c469ccf5f52daf223b91166e6866d42d6983a3b374 AS package
COPY --from=build /rootfs/. .
RUN test -x /tvc_app
RUN sha256sum /tvc_app | awk '{print "SHA256=" $1}'
